### ISSUE TITLE
Inconsistency in File Links

### ISSUE THREAD

**Issue by Xarthisius** [CitrineInformatics/taurus-documentation#59]
The following example https://github.com/CitrineInformatics/gemd-docs/blob/13a7eca5071923207048f0a09a21f42c8e3a7c9f/docs/specification/attributes.md#examples

has `file_links` property expressed as `{"filename":..., "link":...}`. 

Definition of File Links however is given as `{"filename":..., "url":...}` (see https://github.com/CitrineInformatics/gemd-docs/blob/13a7eca5071923207048f0a09a21f42c8e3a7c9f/docs/specification/file-links.md).

Is that a typo or are both forms acceptable (and `link` is defined as relative path to something)?

**Comment by bfolie** [comment]
Thanks for catching that @Xarthisius. It's out of date documentation. We originally used "link" but switched to "url" some time ago. I'll update the example.
